name: Sync Bitget → Google Sheets

on:
  schedule:
    - cron: "*/30 * * * *"   # roda a cada 30 min
  workflow_dispatch: {}       # permite rodar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r sync/requirements.txt
      - env:
          BITGET_API_KEY: ${{ secrets.BITGET_API_KEY }}
          BITGET_API_SECRET: ${{ secrets.BITGET_API_SECRET }}
          BITGET_PASSPHRASE: ${{ secrets.BITGET_PASSPHRASE }}
          GOOGLE_SA_JSON: ${{ secrets.GOOGLE_SA_JSON }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          SHEET_TRADES_NAME: ${{ secrets.SHEET_TRADES_NAME }}
          SYMBOLS: ${{ secrets.SYMBOLS }}
        run: python sync/fills_to_sheet.py
